version: '2.0'

services:

  nginx:
    container_name: ls_frontend
    image: nginx:1.13

  php71:
    container_name: ls_php71
    image: eaudeweb/php-fpm:7.1-1.0.1
    depends_on:
      - db

  php56:
    container_name: ls_php56
    image: eaudeweb/php-fpm:5.6-1.0.1
    depends_on:
      - db

  db:
    container_name: ls_db
    image: mariadb:10.3
    volumes:
      - ./conf-mysqld/server.cnf:/etc/mysql/conf.d/server.cnf

  mail:
    container_name: ls_mail
    image: eaudeweb/mailtrap
